FROM node:18-alpine

RUN echo ${PWD}
# Create app directory
RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

# Install dependencieså
COPY package.json /usr/src/app 

RUN npm install
# Bundle app source
COPY . .
# Expose the application port
EXPOSE 8080

CMD [ "npm", "run", "dev"]