services: 
  db:
    image: mysql:8.0
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s
    networks:
      - nodejs-mysql-network
  service1:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    
    expose:
      - "8080"
    networks:
      - nodejs-mysql-network
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      db:
        condition: service_healthy
# Names our volume
volumes:

  my-db:
networks:
  nodejs-mysql-network:
    name: nodejs-mysql-network